name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: 'Level 1: Appointment Class'
      id: level-1-appointment-class
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Level 1: Appointment Class'
        setup-command: curl -O https://raw.githubusercontent.com/itsjustej/MP1Test/refs/heads/main/Level1Test.java
          && javac -d . $(find . -name "Appointment.java") Level1Test.java
        command: java Level1Test
        timeout: 2
        max-score: 20
    - name: Level 2 - Patient Class
      id: level-2-patient-class
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Level 2 - Patient Class
        setup-command: curl -O https://raw.githubusercontent.com/itsjustej/MP1Test/refs/heads/main/Level2Test.java
          && javac -d . $(find . -name "Appointment.java") $(find . -name "Patient.java")
          Level2Test.java
        command: java Level2Test
        timeout: 2
        max-score: 25
    - name: Level 3 - Medical Office
      id: level-3-medical-office
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Level 3 - Medical Office
        setup-command: bash curl -O https://raw.githubusercontent.com/itsjustej/MP1Test/refs/heads/main/Level3Test.java
          && javac -d . $(find . -name "*.java") Level3Test.java
        command: java Level3Test
        timeout: 2
        max-score: 30
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LEVEL-1-APPOINTMENT-CLASS_RESULTS: "${{steps.level-1-appointment-class.outputs.result}}"
        LEVEL-2-PATIENT-CLASS_RESULTS: "${{steps.level-2-patient-class.outputs.result}}"
        LEVEL-3-MEDICAL-OFFICE_RESULTS: "${{steps.level-3-medical-office.outputs.result}}"
      with:
        runners: level-1-appointment-class,level-2-patient-class,level-3-medical-office
